# pushgateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels }}
  template:
    spec:
      containers:
        - name: pushgateway
          image: {{ .Values.image.repository }} # Update to the desired version
          ports:
            - containerPort: 9091