# pushgateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
       app: {{ .Values.deployment.labels.app }}
       env: {{ .Values.deployment.labels.env }}
  template:
    metadata:
      name:  {{ .Values.pod.name }}
      labels:
        app: {{ .Values.deployment.labels.app }}
        env: {{ .Values.deployment.labels.env }}
    spec:
      containers:
        - name: pushgateway
          image: {{ .Values.image.repository }} # Update to the desired version
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: pushgateway-data-volume
              mountPath: /data
      volumes:
         - name: pushgateway-data-volume
           persistentVolumeClaim:
             claimName: prom-pg-pvc
