# pushgateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: prometheus
  selector:
    app: pushgateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9091
  type: {{ .Values.service.type }} # You can adjust the service type if needed